### ISSUE TITLE
I'm learning, ready to help

### ISSUE THREAD

**Issue by RoofTyler** [hexx112/scriblet#1]
Yo dude, I'm sha1! After them comments I downloaded a copy to play around with and i'm feeling pretty confident.

>    I added 3 "themes" (just different colours):    green, dark and white

>    I added a "top bar" like windows sticky notes but nothing apart from Delete, New or Drag works

>    Added a bottom "status" bar cause I plan to send requests to a server to store notes and show response there

>    Removed time as it wasn't for me but could just relocate it.

Feel free to copy anything what I changed if you wish but my code right now isn't good either!

**Comment by hexx112** [comment]
FUCK that's a lot of features, thanks man i'll try to manually merge some of the code into the main branch.

**Comment by hexx112** [comment]
Do you mind if I just manually copy some of your changes?

**Comment by RoofTyler** [comment]
Go for it dude! Haven't touched it since I posted that but I might play around again tonight with it.
Should we make a list of things to do and assign each other and do them things whenever we can? If you're up for that of course!

**Comment by hexx112** [comment]
Totally! Do you have slack?

**Comment by hexx112** [comment]
https://join.slack.com/t/scriblet/shared_invite/enQtMjg5NTE4NzIzNzYxLTQ4YWZmMzljZWMzZDMyNmViYjA5N2EzYzE4ZDYwMzcxNjg0N2M0NTJiNDU0NWY2NmY2NzQ5MDZmOGVhOGJmODE

Ok join that

**Comment by RoofTyler** [comment]
I've joined!
